### ISSUE TITLE
建議 refactor 的玩意兒

### ISSUE THREAD

**Issue by EricTsai83** [chunyulo-code/mind-chat#42]
### 1
[程式碼位置](https://github.com/chunyulo-code/mind-chat/blob/4c58ed80969859ebd98f70ed72f765fcd6c538e1/src/app/components/DeleteMapModal.tsx#L40)
```js
onClick={() => {
  mapIdToDelete && deleteMap(mapIdToDelete)
}}>
```

### 2
[程式碼位置](https://github.com/chunyulo-code/mind-chat/blob/4c58ed80969859ebd98f70ed72f765fcd6c538e1/src/app/components/Header.tsx#L3)
沒用就刪了唄

### 3
[程式碼位置](https://github.com/chunyulo-code/mind-chat/blob/4c58ed80969859ebd98f70ed72f765fcd6c538e1/src/app/components/Header.tsx#L86)
沒有 className 就刪了唄

### 4
[程式碼位置](https://github.com/chunyulo-code/mind-chat/blob/4c58ed80969859ebd98f70ed72f765fcd6c538e1/src/app/hooks/useContextMenu.ts#L17)
還是要加一下 dependency 比較好

### 5
[程式碼位置](https://github.com/chunyulo-code/mind-chat/blob/4c58ed80969859ebd98f70ed72f765fcd6c538e1/src/app/map/left/LeftBar.tsx#L72C11-L72C11)
1. 雖然 MDN 官方是寫 for (let entry of entries)，但我看到 https://ithelp.ithome.com.tw/articles/10278080 是寫forEach
2. forEach 也是比較好閱讀的語法

### 6
[程式碼位置](https://github.com/chunyulo-code/mind-chat/blob/4c58ed80969859ebd98f70ed72f765fcd6c538e1/src/app/map/left/MapItem.tsx#L11)
FSDeleteMap 套件沒有用到，可刪

### 7
[程式碼位置](https://github.com/chunyulo-code/mind-chat/blob/4c58ed80969859ebd98f70ed72f765fcd6c538e1/src/app/map/left/MapItem.tsx#L36)
```js
  function blurInput(e: React.KeyboardEvent<HTMLInputElement>) {
    if (e.key === "Enter") {
      if (inputRef.current) {
        inputRef.current.blur();
        dispatch(setEditableMapId(undefined));
      }
    }
  }
```

可以簡化為
```js
function blurInput(e: React.KeyboardEvent<HTMLInputElement>) {
  if (e.key === "Enter" && inputRef.current) {
    inputRef.current.blur();
    dispatch(setEditableMapId(undefined));
  }
}
```

### 8
[程式碼位置](https://github.com/chunyulo-code/mind-chat/blob/4c58ed80969859ebd98f70ed72f765fcd6c538e1/src/app/map/main/mindChatNodes/CustomNode.tsx#L3)
可以簡化為
```js
import {Handle, Position, NodeToolbar, Node} from "reactflow"; 
```

### 9
[程式碼位置](https://github.com/chunyulo-code/mind-chat/blob/4c58ed80969859ebd98f70ed72f765fcd6c538e1/src/app/map/main/Canvas.tsx#L12)

```js
  useEffect(() => {
    if (canvasRef) {
      const canvas = canvasRef.current;
      if (canvas) {
        canvas.height = window.innerHeight * 2;
        canvas.width = window.innerWidth * 2;
        canvas.style.width = `${window.innerWidth}px`;
        canvas.style.height = `${window.innerHeight}px`;
        const context = canvas.getContext("2d", { willReadFrequently: true });

        if (context) {
          context.scale(2, 2);
          context.lineCap = "round";
          context.strokeStyle = color;
          context.lineWidth = 5;
          context.fillStyle = "rgba(31,40,51,0.1)";
          context.fillRect(0, 0, canvas.width, canvas.height); // 填滿整個畫布

          if (ctx) {
            ctx.current = context;
          }
        }
      }
    }
  }, []);
```
我比較喜歡以下的寫法，但你的寫法比較安全
```js
  useEffect(() => {
    if (canvasRef) {
      const canvas = canvasRef.current!;
      canvas.height = window.innerHeight * 2;
      canvas.width = window.innerWidth * 2;
      canvas.style.width = `${window.innerWidth}px`;
      canvas.style.height = `${window.innerHeight}px`;
      const context = canvas.getContext("2d", {willReadFrequently: true})!;
      context.scale(2, 2);
      context.lineCap = "round";
      context.strokeStyle = color;
      context.lineWidth = 5;
      context.fillStyle = "rgba(31,40,51,0.1)";
      context.fillRect(0, 0, canvas.width, canvas.height); // 填滿整個畫布
      if (ctx) {
        ctx.current = context;
      }
    }
  }, []);
```

### 10
[程式碼位置](https://github.com/chunyulo-code/mind-chat/blob/4c58ed80969859ebd98f70ed72f765fcd6c538e1/src/app/map/main/Outline.tsx#L10)
css 多了一個空白鍵

### 11
[程式碼位置](https://github.com/chunyulo-code/mind-chat/blob/4c58ed80969859ebd98f70ed72f765fcd6c538e1/src/app/map/right/Library.tsx#L17C1-L17C49)
沒用到auth，建議移除

### 12
[程式碼位置](https://github.com/chunyulo-code/mind-chat/blob/4c58ed80969859ebd98f70ed72f765fcd6c538e1/src/app/map/right/Spolight.tsx#L54C1-L54C1)
有any ，建議改成下方程式碼
```js
  const colorScale = scaleLinear()
    .domain([
      Math.min(...sortedData.map((d) => d.value)),
      Math.max(...sortedData.map((d) => d.value)),
    ])
    .range(["#c5c6c7", "#66fcf1"] as Iterable<number>);
```

### 13
[程式碼位置](https://github.com/chunyulo-code/mind-chat/blob/4c58ed80969859ebd98f70ed72f765fcd6c538e1/src/app/map/tools/FormatConverter.tsx#L115C1-L115C1)

```js
<div className="absolute left-5 top-5 z-50 flex gap-2 rounded-lg bg-mindchat-bg-dark-darker px-5 py-2 shadow-sm shadow-gray-900">
```

tailwind css 好長喔！個人偏好，我覺得透過下方方式分段會好一點
```js
className={`
  flex
  h-screen
  w-screen
  flex-col
  items-center
  justify-center
  bg-gray-800
`}
```

### 14
[程式碼位置](https://github.com/chunyulo-code/mind-chat/blob/4c58ed80969859ebd98f70ed72f765fcd6c538e1/src/app/map/tools/Images.tsx#L40)
原本長這樣
```js
className={`${
  imageUrl === selectedImage ? "border-2 border-mindchat-primary" : ""
}`}
```
可以改成這樣
```js
className={
  imageUrl === selectedImage ? "border-2 border-mindchat-primary" : ""
}
```

### 15 
[程式碼位置](https://github.com/chunyulo-code/mind-chat/blob/4c58ed80969859ebd98f70ed72f765fcd6c538e1/src/app/map/page.tsx#L29)

```js
  const clearCanvas: ClearCanvas = () => {
    const canvas = canvasRef.current;
    if (canvas) {
      const context = canvas.getContext("2d", { willReadFrequently: true });
      if (context) {
        context.clearRect(0, 0, canvas.width, canvas.height);
      }
    }
  };
```
我比較喜歡以下寫法
```js
  const clearCanvas: ClearCanvas = () => {
    const canvas = canvasRef.current;
    if (canvas) {
      const context = canvas.getContext("2d", { willReadFrequently: true })!;
      context.clearRect(0, 0, canvas.width, canvas.height);
    }
  };
  
```

### 16
[程式碼位置](https://github.com/chunyulo-code/mind-chat/blob/4c58ed80969859ebd98f70ed72f765fcd6c538e1/src/app/utils/firebaseAuth.ts#L9)
一堆沒用到的套件是怎樣，改成這個！！
```js
import { auth } from "./firebase";
```

### 17
[程式碼位置](https://github.com/chunyulo-code/mind-chat/blob/4c58ed80969859ebd98f70ed72f765fcd6c538e1/src/app/page.tsx#L1C14-L1C14)
感覺你首頁大部分的玩意兒都是靜態的，不需要用state去管理，把需要用到 state 的 component 拆出去，有機會使用 SSR 面試的時候 show 一波，建議修改
![截圖 2023-07-21 上午8 58 38](https://github.com/chunyulo-code/mind-chat/assets/52527831/efa9c14a-9707-44d7-a693-3100ebfdf3ed)

### 18
[程式碼位置](https://github.com/chunyulo-code/mind-chat/blob/4c58ed80969859ebd98f70ed72f765fcd6c538e1/src/app/page.tsx#L3)
套件沒用就刪了唄

**Comment by chunyulo-code** [comment]
Thx for your review
